### ISSUE TITLE
Edited table exceeds char limit

### ISSUE THREAD

**Issue by seallard** [seallard/botworm#28]
```bash
app_1       | Traceback (most recent call last):
app_1       |   File "./botworm.py", line 60, in <module>
app_1       |     main()
app_1       |   File "./botworm.py", line 42, in main
app_1       |     rec_index = reddit.edit_table(bot_comment, recommendations)
app_1       |   File "/app/utils/reddit.py", line 82, in edit_table
app_1       |     bot_comment.edit(table)
app_1       |   File "/usr/local/lib/python3.8/site-packages/praw/models/reddit/mixins/editable.py", line 43, in edit
app_1       |     updated = self._reddit.post(API_PATH["edit"], data=data)[0]
app_1       |   File "/usr/local/lib/python3.8/site-packages/praw/reddit.py", line 555, in post
app_1       |     return self._objector.objectify(data)
app_1       |   File "/usr/local/lib/python3.8/site-packages/praw/objector.py", line 170, in objectify
app_1       |     raise APIException(*errors[0])
app_1       | praw.exceptions.APIException: TOO_LONG: 'this is too long (max: 10000)' on field 'text'
```

**Comment by seallard** [comment]
The char limit was set to 9800. It seems like a single row in a table can exceed 200 chars.
