### ISSUE TITLE
Locked threads

### ISSUE THREAD

**Issue by seallard** [seallard/botworm#29]
```bash
app_1       | Traceback (most recent call last):
app_1       |   File "./botworm.py", line 60, in <module>
app_1       |     main()
app_1       |   File "./botworm.py", line 55, in main
app_1       |     reddit.post_comments(post, bot_comments)
app_1       |   File "/app/utils/reddit.py", line 37, in post_comments
app_1       |     post = post.reply(comment.text)
app_1       |   File "/usr/local/lib/python3.8/site-packages/praw/models/reddit/mixins/replyable.py", line 33, in reply
app_1       |     comments = self._reddit.post(API_PATH["comment"], data=data)
app_1       |   File "/usr/local/lib/python3.8/site-packages/praw/reddit.py", line 555, in post
app_1       |     return self._objector.objectify(data)
app_1       |   File "/usr/local/lib/python3.8/site-packages/praw/objector.py", line 170, in objectify
app_1       |     raise APIException(*errors[0])
app_1       | praw.exceptions.APIException: THREAD_LOCKED: 'Comments are locked.' on field 'parent'
```

**Comment by seallard** [comment]
https://github.com/seallard/botworm/commit/994bbe16aecf03b08c72ddc0d122780f73237d50
